### ISSUE TITLE
Rilevamento di Google Maps

### ISSUE THREAD

**Issue by nemobis** [MonitoraPA/monitorapa#26]
La maggior parte delle inclusioni si possono individuare grazie alle chiamate a maps.googleapis.com.

Esempi:
https://www.guardiacostiera.gov.it/
http://www.dovesalute.gov.it/

**Comment by nemobis** [comment]
Un vantaggio di segnalare Google Maps è che esiste già l'utilissimo https://switch2osm.org/

**Comment by loviuz** [comment]
Conviene sostiture il widget di GMaps con quello di Openstreetmap ma da fare attenzione al tile server da usare:

https://wiki.openstreetmap.org/wiki/Tile_servers

Ce ne sono alcuni in UE e che non sono di aziende con sede fuori da UE, quindi potrebbero essere una soluzione affidabile e GDPR-compliant, ad esempio:
```html
<link rel="stylesheet" href="css/leaflet.css">
<script src="js/leaflet.js"></script>

<link rel="stylesheet" href="css/leaflet-gesture-handling.min.css" type="text/css">
<script src="css/leaflet-gesture-handling.js"></script>

<script>
    var map = L.map('map', {
    center: ["45.XXX", "11.XXX"],
    zoom:  7 ,
    gestureHandling: true
    });
    var redIcon = new L.Icon({
    iconUrl: 'images/marker-icon-2x-red.png',
    shadowUrl: 'images/marker-shadow.png',
    iconSize: [25, 41],
    iconAnchor: [12, 41],
    popupAnchor: [1, -34],
    shadowSize: [41, 41]
    });
    L.tileLayer('https://{s}.tile.openstreetmap.de/{z}/{x}/{y}.png', {
    maxZoom: 17,
    attribution: '© OpenStreetMap'
}).addTo(map);
var marker = L.marker(["45.XXX", "11.XXX"], {icon: redIcon}).addTo(map);
marker.bindPopup("Contenuto Popup").openPopup();
</script>
```

**Comment by loviuz** [comment]
Giusto per capire come funziona: ho visto lo script di Google Fonts e alla fine viene ritornata una stringa vuota se non vengono trovati fonts, altrimenti viene ritornato un JSON con la lista fonts. Per Google Maps occorre gestirlo allo stesso modo? Ho notato ad esempio che se sulla console di debug del browser digito google.maps.version ottengo il numero di versione di Google Maps. Potrebbe essere questo un check valido da sviluppare?

**Comment by Shamar** [comment]
La logica è che devi tirar fuori delle prove inconfutabili della presenza del problema.

Il numero di versione di Google Maps potrebbe essere un ottimo candidato.

Poi bisogna sempre testarla sul campo, verificando i positivi identificati dal test (accertandosi che il problema ci sia davvero) e i negativi (accertandosi che non ci sia davvero).

Di solito il ciclo di sviluppo comporta un paio di iterazioni in cui trovi tanti falsi negativi (e correggi / estendi il test per identificarli come positivi) e alcuni falsi positivi (e correggi il test per escluderli).

Meglio avere 500 falsi negativi che 1 falso positivo.

**Comment by loviuz** [comment]
ok, era giusto per avere conferma di come funzionava il tutto al di là che basti vedere la versione di maps. grazie!
