### ISSUE TITLE
Rilevamento di Microsoft Azure

### ISSUE THREAD

**Issue by nemobis** [MonitoraPA/monitorapa#41]
È impossibile fare una valutazione unica per qualunque cosa ospitata in Amazon AWS, ma alcuni casi sono semplici, come le chiamate dirette a certi servizi SaaSS di Microsoft. C'è un bell'elenchino in https://docs.microsoft.com/en-us/azure/security/fundamentals/azure-domains , alcuni li chiamano senza nemmeno mascherarli dietro un CNAME.

Piuttosto comuni sono msecnd.net, azureedge.net, windows.net.

**Comment by nemobis** [comment]
@Shamar ma è giusto che ci sia un `"` nell'ultima riga di https://github.com/MonitoraPA/monitorapa/blob/main/cli/check/browsing/hosts/508-microsoft.hosts ?

**Comment by Shamar** [comment]
decisamente no!

Grazie della segnalazione!

**Comment by Shamar** [comment]
fixed in 992c7fd37db7f23889d407902612ddbf9a40656c
