### ISSUE TITLE
GA su developers italia

### ISSUE THREAD

**Issue by vixrt** [MonitoraPA/monitorapa#5]
Sbaglio o developers italia https://developers.italia.it/ usa GA?

**Comment by Shamar** [comment]
Non sbagli, ma non era nella lista dei siti istituzionali della PA che scarichiamo dal sito dell'AgID.

Se vuoi scrivere loro chiedendo di rimuovere Google Analytics ed adottare Web Analytics Italia, hai la nostra benedizione.

Adesso hai anche dalla tua il comunicato del Garante della Privacy italiano:

```
l’Autorità richiama all’attenzione di tutti i gestori italiani di siti web, 
pubblici e privati, l’illiceità dei trasferimenti effettuati verso gli 
Stati Uniti attraverso GA, anche in considerazione delle numerose 
segnalazioni e quesiti che stanno pervenendo all’Ufficio. 
```
https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/9782874
