### ISSUE TITLE
versione non sicura attiva

### ISSUE THREAD

**Issue by vixrt** [MonitoraPA/monitorapa#7]
Il sito http:// è in funzione, insieme a quello https://
In teoria la best practice è fare che http faccia redirect su https

**Comment by Shamar** [comment]
Al momento si tratta di una scelta consapevole.

Il sito è completamente pubblico e statico, non contiene form o script di alcun tipo.
Obbligare tutti ad usare HTTPS, in questo caso, non aumenterebbe la riservatezza della visita perché dalla dimensione dei file che scarichi è possibile identificare cosa leggi.

Lasciando la versione HTTP disponibile però garantiamo una maggiore disponibilità, perché HTTP, contrariamente ad HTTPS, può essere oggetto di caching da parte dei proxy intermedi. Ovviamente questo comporta un rischio per l'integrità: per questo chi lo desidera ha accesso alla versione HTTPS.

Insomma, **in questo momento** la soluzione ottimale consiste nel permettere l'accesso sia via HTTP che via HTTPS.

Laddove dovessimo introdurre form o qualsiasi altra forma di interattività, introdurremo ovviamente il redirect che proponi.
