### ISSUE TITLE
Missing / in  manual.md

### ISSUE THREAD

**Issue by girolamodaschio** [MonitoraPA/monitorapa#8]
Right before [script-execution](https://github.com/MonitoraPA/monitorapa/blob/main/cli/MANUAL.md#script-execution) chapter, there is a missing slash in 
 ```bash
pip install -r /clirequirements.txt
```

**Comment by Shamar** [comment]
Thanks @girolamodaschio, sorry for the delay... we were all focused on non technical stuffs and we missed your PR... sorry!
